"""fixed category relationship with stream

Revision ID: 67de5100f53c
Revises: dc14406f9a77
Create Date: 2023-03-14 17:45:34.769367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67de5100f53c'
down_revision = 'dc14406f9a77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
